device: cpu
pretrained_optim_path: null
pretrained_param_path: null
inference_param_path: stage01_compose/ckpt/compose_model_pop1k7_finetuned_loss0.387.bin

model:
  d_word_embed: 512
  pre_lnorm: True
  decoder:
    n_layer: 12
    n_head: 8
    d_model: 512
    d_ff: 2048
    dropout: 0.1
    mem_len: 0
    tgt_len: 2400

data:
  data_dir: compose-and-embellish-pop1k7/datasets/stage01_compose/pop1k7_finetune
  train_split: compose-and-embellish-pop1k7/datasets/stage01_compose/data_splits/pop1k7_finetune_train.pkl
  val_split: compose-and-embellish-pop1k7/datasets/stage01_compose/data_splits/pop1k7_finetune_valid.pkl
  vocab_path: stage01_compose/vocab/remi_jtrans_vocab.pkl
  batch_size: 2
  max_n_seg: 1

training:
  trained_steps: 0
  trained_epochs: 0
  warmup_steps: 200
  lr_decay_steps: 500000
  max_lr: 1.0e-4
  min_lr: 1.0e-5
  max_epoch: 40
  val_interval: 1
  log_interval: 50

output:
  ckpt_dir: ckpt/stage01_compose_finetune_pop1k7_seq2400
  ckpt_interval: 4
